export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL'
export const POST_PRODUCT= 'POST_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'

export const GET_ALL_STORES = 'GET_ALL_STORES';
export const GET_STORES_DETAIL = 'GET_STORES_DETAIL';



