export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL'
export const POST_PRODUCT= 'POST_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'



